//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mahasiswa
    {
        public Mahasiswa()
        {
            this.Enrolls = new HashSet<Enroll>();
        }
    
        public int IdMahasiswa { get; set; }
        public string NamaMahasiswa { get; set; }
        public string Nim { get; set; }
        public int Angkatan { get; set; }
        public string StatusMahasiswa { get; set; }
        public string Prodi { get; set; }
        public string AlamatTinggal { get; set; }
        public string Handphone { get; set; }
        public string DosenPembimbing { get; set; }
        public Nullable<int> Semester { get; set; }
    
        public virtual ICollection<Enroll> Enrolls { get; set; }
    }
}
