//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MataKuliah
    {
        public MataKuliah()
        {
            this.Enrolls = new HashSet<Enroll>();
        }
    
        public int IdMakul { get; set; }
        public string KodeMakul { get; set; }
        public string NamaMakul { get; set; }
        public string Kelas { get; set; }
        public Nullable<int> Sks { get; set; }
        public string Sifat { get; set; }
        public string Jadwal { get; set; }
        public Nullable<int> RekomendasiPengambilan { get; set; }
        public string DosenPengajar { get; set; }
    
        public virtual ICollection<Enroll> Enrolls { get; set; }
    }
}
